Fix/oracle blocking
Switcheo/cometbft pull request #8
Opened 2024-12-06 10:53 UTC by yan-soon

- add getStateWithTimeout() so that oracle voting is not blocked during long software upgrades
- drop votes from oracle vote channel when size hits 1/2 of cap

2024-12-06 11:23 UTC, holyxiaoxin commented on oracle/reactor.go
> +		TIMEOUT := time.Second * 5
Comment what 5seconds

2024-12-06 11:25 UTC, holyxiaoxin commented on oracle/service/runner/runner.go
> +			TIMEOUT := time.Second * 3
Comment why 3s

2024-12-09 04:10 UTC, RavenXce requested changes

2024-12-09 04:10 UTC, RavenXce commented on oracle/reactor.go
> +		TIMEOUT := time.Second * 5
why is this caps

2024-12-09 04:10 UTC, RavenXce commented on oracle/service/runner/runner.go
> +			TIMEOUT := time.Second * 3
3s seems very low. why is the var caps?

2024-12-09 04:10 UTC, RavenXce commented on oracle/service/runner/runner.go
> +		if len(oracleInfo.SignVotesChan) >= cap(oracleInfo.SignVotesChan)/2 {
why do we not log here?
why not just -1?

2024-12-09 04:10 UTC, RavenXce commented on oracle/service/runner/runner.go
> +				if currTimestampsLen == 0 {
why is this not just `||` with L131

2024-12-09 08:10 UTC, tehkohrz requested changes

2024-12-09 08:10 UTC, tehkohrz commented on oracle/service/runner/runner.go
> +			timeout := time.Second * 3
change to prune interval

2024-12-10 10:36 UTC, holyxiaoxin approved these changes

2024-12-11 09:37 UTC, merged